apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqldatabases.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                size:
                  type: string
                storage:
                  type: string
          required:
            - spec
  scope: Namespaced
  names:
    plural: mysqldatabases
    singular: mysqldatabase
    kind: MySQLDatabase
